### ISSUE TITLE
"onClick" attribute for Actor Label only runs the first time.

### ISSUE THREAD

**Issue by jpsgamboa** [czyzby/gdx-lml#18]
I don't know if this is expected behavior, but I've set an `onclick` in some `Labels `but the linked `LmlAction` only runs the first time I click.
Changing the `Label` to a `TextButton` works as aspected.

The reason I'm using labels is because I'm populating a `Tree` and don't want the background that buttons have. Maybe I'm missing a better alternative?
I noticed you used a `Table` and toggle buttons on `gdx-lml-tests` and like the look, but wouldn't allow me to achieve the tree child collapsing and expanding behavior.

I'm trying to achieve this look as seen on VisEditor:
![aa](https://cloud.githubusercontent.com/assets/12597232/14589273/02cc28aa-04d6-11e6-8dde-641e1636cfb6.PNG)

**Comment by czyzby** [comment]
This is the click listener attachment code:
```
        actor.addListener(new ClickListener() {
            @Override
            public void clicked(final InputEvent event, final float x, final float y) {
                action.consume(actor);
            }
        });
```
Nothing special about this, really, it should fire each time. Try the following in `gdx-lml-vis-tests`: `<label onclick="print">Hello!</label>`.

```
    @LmlAction("print")
    void print(final Label label) {
        System.out.println(label.getText());
    }
```
As expected listener fires each time:
```
Hello!
Hello!
Hello!
```
*Maybe* the tree does something to its children, but I doubt it.

**Comment by czyzby** [comment]
By the way, the `VisEditor` seems to be using a `TabbedPane`.

**Comment by czyzby** [comment]
Hahah, I know what's going on. You have to click **directly on the label**. The tree highlights the whole area that it fills, but the listener fires *only* when you click *directly* on the text. I guess this is what happened, and you thought that the listener was somehow removed. Try the following (with the print method from previous comments):
```
<tree>
<label onClick=print>H</label>
<label onClick=print>E</label>
<label onClick=print>L</label>
<label onClick=print>L</label>
<label onClick=print>O</label>
</tree>
```
When you click on the letter, it will be printed. If you click on the highlighted area to the right/left, nothing will happen. Can you confirm that you're having this issue?

My suggestion to resolve this is using a `onChange` attribute on the tree widget rather than separate listeners for each child.

**Comment by jpsgamboa** [comment]
Ah silly me. Went completely over my head! Sorry for the useless post.
For future visitors, the following works nicely:
```
<tree id="tree" onchange="handleSelection">
    <label node="true" text="First">
        <label node="true" text="Sub-First"/>
    </label>
    <label node="true" text="Second"/>
    <label node="true" text="Third"/>
</tree>
```
And looks great:
![qqq](https://cloud.githubusercontent.com/assets/12597232/14590830/b6710e4a-04fc-11e6-94f9-9498925bb22b.PNG)

**Comment by czyzby** [comment]
I think `node="true"` is only necessary if you want the actor to be an "openable" tree node. If it's a child-only label (has no tree children), you can try omitting the attribute.
