### ISSUE TITLE
DTD file

### ISSUE THREAD

**Issue by voidburn** [czyzby/gdx-lml#2]
It would be nice to have a DTD file for the lml spec, so editors can validate and suggest proper document structure when writing lml templates.

**Comment by czyzby** [comment]
`LmlSyntax`-to-DTD is on my TODO list, but I won't make any promises in which version it will appear. Since syntax can change (users can add their custom tags, attributes and macros), I want to make it possible to generate a customized DTD file according to the current syntax object settings. There will probably be some issues - I'm not sure if `@` is a valid XML tag opening char, for example, so macros might need a different marker. Anyway, I'll definitely let you know in this issue when the DTD converter is ready.

**Comment by czyzby** [comment]
*DTD* file generator will be available in `LML 1.5.1.9.2`. See https://github.com/czyzby/gdx-lml/tree/master/dtd
