### ISSUE TITLE
LSS: LML Style Sheets

### ISSUE THREAD

**Issue by czyzby** [czyzby/gdx-lml#27]
LML should support simple styling sheets with CSS-like syntax, which would allow to set up default values for common, repetitive attributes in chosen tags. Simple inheritance should be supported.

**Comment by czyzby** [comment]
@jpsgamboa @metaphore If you guys still use LML, I'd appreciate if you used LML `1.8.1.9.4-b1` and checked out the new [LML style sheets](https://github.com/czyzby/gdx-lml/wiki/Style-sheets).

**Comment by metaphore** [comment]
The idea is brilliant and it should definitely fill the gap for defining application wide widget styles. But I feel like there is still no convenient way to define style for only some particular elements (like classes in HTML). Maybe is it somehow possible to implement class-like attribute dedicated for use directly with LSS?

I like the `<:style/>` macro, but what if I need to define a lot of styles for a whole template (few templates)? I think it would be cool to have ability to apply entire LSS document to template through macro (just like `<:import/>` works with templates).

**Comment by czyzby** [comment]
Well, implementing CSS-like selectors is certainly possible, but certainly more complicated than the current implementation. I would have to introduce some kind of predicates to style containers that would check conditions before applying style to the tag's actor - a bit more complex than the current naive map-of-maps approach.

Styles importing is actually a very good idea, though. See #38.

**Comment by metaphore** [comment]
Hm, after short look at style related classes structure and `AbstractActorLmlTag#addDefaultAttributes()` I can think of easy solution like use extra map of styles for particular "classes" (HTML analogy) alongside with default map. Class can be defined with same old fashion `class` attribute and since we already have map of named attributes when we applying our default styles (`AbstractLmlTag#getNamedAttributes()`), we can check for that attribute and if it matches to one of defined styles for particular classes, apply style in the same way as default, but right after it. It's of course will be not much powerful as CSS selectors, but still let us define styles for limited amount of specific widgets.

Same could be done for IDs, but I doubt overhead and extra parser complexity will worth it, because we still can do the same using only classes approach.

What do you think?

**Comment by czyzby** [comment]
It would break existing applications, as I was stupid enough to use `class` attribute as a synonym for `style`. Doesn't solve the case of nested actors ("apply style to all children of tables"...), but it seems reasonable. Thanks for your suggestions.

**Comment by metaphore** [comment]
Hehe, yeah, I was a bit surprised to see `class` attribute back in a my first try of LML :)

**Comment by czyzby** [comment]
LibGDX `Skin` (and the widget styles it stores) is the kinda-sorta CSS of Scene2D, hence the name. LSS is the new kid on the block, I wasn't planning on making a CSS parser as well.

**Comment by czyzby** [comment]
Resolved in `1.8` branch.
