### ISSUE TITLE
SelectBoxLmlTag forces to use only strings for items

### ISSUE THREAD

**Issue by metaphore** [czyzby/gdx-lml#29]
I'm trying to unify some filling code for ```VisSelectBox```  in my LML.
Like so:
```
<visselectbox>
    <:evaluate method="fillWithItems" id="selectBox"/>
</visselectbox>
```

And action looks like this:
```
@LmlAction("fillWithItems")
public void fillWithItems(VisSelectBox selectBox) {
    Array<Item> items= new Array<>();
    // Fill items with objects ...
    selectBox.setItems(array);
}
```

The problem comes from parser that calls ```SelectBoxLmlTag#doOnTagClose()```, precisely next line:
```
// Forcing items update.
getSelectBox().setItems((String[]) getSelectBox().getItems().toArray(String.class));
```
and I get ```java.lang.ArrayStoreException```.

I want to reference real objects and not plain strings letter. Maybe I'm wrong at something and should use another approach to fill my collection based widgets with same data?

Thanks!

**Comment by czyzby** [comment]
You can use `oncreate="fillWithItems"` attribute in select box instead of `<:evaluate>` tag.

Select box implementation is... problematic. When the line that you posted was not invoked, select box was not updated and did not display the items properly. I might have to take a look at it to make it more generic.

**Comment by czyzby** [comment]
Fixed. Use `1.8.1.9.3-SNAPSHOT` release if you badly need this feature.
