### ISSUE TITLE
Duplicate robovm.xml in gdx-lml-1.7.1.9.3.jar

### ISSUE THREAD

**Issue by ghandhikus** [czyzby/gdx-lml#46]
Duplicate file stops gradlew from building.
http://i.imgur.com/5tGDQls.png

**Comment by kotcrab** [comment]
See https://github.com/czyzby/gdx-lml/issues/41#issuecomment-252410971.

**Comment by czyzby** [comment]
As @kotcrab pointed out, this is a common issue. Android fails to compile when you include multiple libraries that support RoboVM, since they all contain RoboVM meta-data file. [See this configuration file](https://github.com/czyzby/gdx-setup/blob/master/src/main/kotlin/com/github/czyzby/setup/data/platforms/android.kt#L116-L130) to resolve this.

**Comment by czyzby** [comment]
Imho this should be by the `gdx-setup` application to Android `build.gradle` file by default, so I created an issue in the official LibGDX repository.

**Comment by czyzby** [comment]
OK, sources were included in the jar for some reason, which caused duplication of `robovm.xml` in the jar. You can use the latest snapshot releases (`1.9.1.9.4` as of writing this issue) without the duplicated file, but - to be honest - you should still add the excludes to your Android Gradle file to prevent these sort of issues from happening.
