### ISSUE TITLE
Conditional macro <:if:else/> not work with "test" attribute

### ISSUE THREAD

**Issue by JajanJawa** [czyzby/gdx-lml#50]
my lml:
```xml
<:if test="{platform}=Desktop"><textfield id="email" /><:if:else /><selectbox id="email"/></:if>
```

it's say: No macro tag provider found for name: if:else

**Comment by czyzby** [comment]
Yeah, I think the parser is pretty naive when looking for the `else` tag and will only accept `<:if:else/>` (without the space). I'll look into it.

**Comment by czyzby** [comment]
Damn. I'm pretty sure I used a regex to detect this if-else "separator" once, but it looks like switched it to a literal for speed, GWT compatibility or whatever reason. Since LibGDX 1.9.5 seems bugged (GWT fails to compile), I'll wait until 1.9.6 and try fix it somehow before the release. Omit the space for now.

**Comment by czyzby** [comment]
Oh, God. The workaround feels dirty in so many ways. But yeah, in 1.9.6 you will be able to use no space or a single space in the `else` tag.
