### ISSUE TITLE
Kiwi: Issue with debugging triples on intellij

### ISSUE THREAD

**Issue by johnvanderholt** [czyzby/gdx-lml#57]
So I've been using the kiwi library when a came across a problem. 

This triple 
```
            Triple test = new Triple(1,2,3);
```
Looks like this in the debugger
![selection_007](https://user-images.githubusercontent.com/30025691/28251216-ae818d08-6a78-11e7-8aff-dc6c951b104e.png)

Pairs seem to work just fine though, even though they're also displayed in a weird way.
![selection_006](https://user-images.githubusercontent.com/30025691/28251206-824b692a-6a78-11e7-843c-4e09bac3a436.png)
However when i try to access the third variable, it works just fine.
But not being able to debug them is a problem.
Is there any way to fix this on my end, like something i can change in my settings.
I'm using intellij community edition 2017.1.5, with kiwi1.9.1.9.6.
I mean, I'm loving the library, it would be a shame if i couldn't use the triples because of this.

**Comment by czyzby** [comment]
This is because all tuples storing at least 2 values implement the `Map.Entry` interface for extra convenience, which seems to be a common trend in Java utility libraries. IntelliJ seems to somehow override the `Triple` API with `Map.Entry`, showing you `key`/`value` instead of `first`/`second`/`third`. As far as the implementation goes, [`Triple` does store 3 values](https://github.com/czyzby/gdx-lml/blob/master/kiwi/src/main/java/com/github/czyzby/kiwi/util/tuple/immutable/Triple.java#L19-L21). I'm sorry, but I'm just not sure how could I fix that without removing the `Map.Entry` interface implementation and breaking the API.
