### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by Hellgasm** [czyzby/gdx-lml#90]
@czyzby Are you still working on it? Works with 1.9.8? Is it stable?

**Comment by czyzby** [comment]
> Are you still working on it?

I actively answer questions about the project, but I don't really work on it anymore. I might find some time some day, go through all the issues and address at least the easy ones, but I don't really look forward to it.

I have to admit LML and Autumn were my first libraries, and while I did refactor or rewrote a lot of code later on, the first versions were basically a result of me learning to code. Since there are no automatic tests and the code quality varies at times, you should understand why I'm not super eager to add any new features. A full release requires too much manual testing. Also, checking if my code doesn't break GWT (which next to no one uses) - and debugging if it does - is a huge pain.

> Works with 1.9.8?

It should work with 1.9.8, I don't think there were a lot of breaking changes in LibGDX as far as I recall.

> Is it stable?

As much as a project without unit tests and a few example applications can be. I used my libs on a few game jams and, well, they didn't crash, but I'm also 100% sure there are some bugs that remain overlooked.

---

It used to be my hobby, but I moved away from gamedev and focused on my commercial work. [KTX](https://github.com/libktx/ktx) is the only project I maintain somewhat actively, since I really like Kotlin and there's a ton of unit tests, so I'm not afraid to release a new version when a new LibGDX comes out. Pretty sure we actually found a few LibGDX bugs, since they don't write a lot of tests either. Try it out, it addresses a lot of issues that my libraries do.
